version: '3.8'

services:
  flylib-api:
    build:
      context: .
      dockerfile: FlyLib.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FlyLibDb;User=sa;Password=Your_password123;
      - Storage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFSUFI4Vv2y4E6h9azk6aFtqAZ6hZdtq2w==;BlobEndpoint=http://storage:10000/devstoreaccount1;
    depends_on:
      - db
      - storage

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data: