
name: Test & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test TestFlyLibrary.Tests/TestFlyLibrary.Tests.csproj --no-build --verbosity normal --collect:"XPlat code coverage" --settings TestFlyLibrary.Tests/coverlet.runsettings

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestFlyLibrary.Tests/TestFlyLibrary.Tests/TestResults/**/coverage.cobertura.xml
        verbose: true
